apiVersion: v1
kind: Secret
metadata:
  name: valaxy-resource-service-__stackName__-secret
type: Opaque
data:
  SECRET_DB_PASSWORD: __dbPassword__
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: valaxy-resource-service-__stackName__-__serviceTag__
spec:
  template:
    metadata:
      labels:
        name: valaxy-resource-service-__stackName__-__serviceTag__
      annotations:
        iam.amazonaws.com/role: __rsRoleArn__
    spec:
      containers:
        - name: valaxy-resource-service-__stackName__
          image:  index.docker.io/software/__serviceName__:__serviceTag__
          imagePullPolicy: Always
          volumeMounts:
          - name: domain-cert
            mountPath: /apps/certs
            readOnly: true
          env:
          - name: AWS_ACCOUNT_NO
            value: "__awsAccountNo__"
          - name: AWS_REGION
            value: __awsRegion__
          - name: STACK_NAME
            value: __envName__
          - name: DB_USERNAME
            value: __dbUserName__
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: valaxy-resource-service-__stackName__-secret
                key: SECRET_DB_PASSWORD
          - name: DB_HOST
            value: "__dbHost__"
          - name: DB_PORT
            value: "__dbPort__"
          - name: DB_NAME
            value: __dbName__
          - name: JKS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: __domainName__-jks
                key: truststore-password
          ports:
            - containerPort: 443
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "echo I am Ready !!! > /tmp/healthy"]
            preStop:
              exec:
                command: ["/bin/sh", "-c", "rm /tmp/healthy && sleep 20"]
          readinessProbe:
            exec:
              command: ["/bin/sh", "-c", "cat /tmp/healthy"]
            initialDelaySeconds: 15
            periodSeconds: 5
            failureThreshold: 2
          resources:
            limits:
             cpu: "0.5"
            requests:
             cpu: "0.25"
      volumes:
        - name: domain-cert
          secret:
            secretName: __domainName__-jks
            items:
              - key: truststore
                path: domain.jks
      terminationGracePeriodSeconds: 120
      imagePullSecrets:
      - name: __imagePullSecrete__
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: valaxy-resource-service-__stackName__-__serviceTag__
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: valaxy-resource-service-__stackName__-__serviceTag__
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
